source 'https://api.berkshelf.com'
metadata

cookbook 'nginx'
cookbook 'wordpress'
cookbook 'mysql', git: 'git@github.com:opscode-cookbooks/mysql.git', tag: 'v5.6.1'
cookbook 'mysql-chef_gem', git: 'git@github.com:opscode-cookbooks/mysql-chef_gem', tag: 'v0.0.5'
cookbook 'database', git: 'git@github.com:opscode-cookbooks/database', tag: 'v2.3.1'
cookbook 'postgresql', git: 'git@github.com:loualrid/postgresql.git', branch: 'develop'
cookbook 'application_ruby', git: 'https://github.com/loualrid/application_ruby.git', branch: 'development'
cookbook 'puma', git: 'git@github.com:yourabi/chef-puma.git'
cookbook 'application'
cookbook 'ohai'
cookbook 'build-essential'
cookbook 'rvm', tag: 'v0.9.2', git: 'git@github.com:martinisoft/chef-rvm.git' #heavily test rvm gem (probably still broken)
cookbook 'apt'
cookbook 'redisio', git: 'git@github.com:brianbianco/redisio.git'
cookbook 'haproxy', git: 'git@github.com:SocialCentivPublic/haproxy.git', branch: 'develop'
cookbook 'rabbitmq', git: 'git@github.com:kennonkwok/rabbitmq.git'
cookbook 'postfix', git: 'git@github.com:opscode-cookbooks/postfix'
cookbook 'nodejs', git: 'git@github.com:redguide/nodejs'
cookbook 'sensu', git: 'git@github.com:sensu/sensu-chef'
cookbook 'uchiwa', git: 'git@github.com:sensu/uchiwa-chef'
cookbook 'apache2', git: 'git@github.com:viverae-cookbooks/apache2', tag: 'v2.0.0' #TODO continue to test v3.0.0 and beyond
cookbook 'graphite', git: 'git@github.com:hw-cookbooks/graphite'
cookbook 'sudo', git: 'git@github.com:opscode-cookbooks/sudo'
cookbook 'grafana', git: 'git@github.com:JonathanTron/chef-grafana.git'
cookbook 'elasticsearch', git: 'git@github.com:elasticsearch/cookbook-elasticsearch', tag: '0.3.13'
cookbook 'logstash', git: 'git@github.com:lusis/chef-logstash.git'
cookbook 'graylog2', git: 'git@github.com:Graylog2/graylog2-cookbook.git'
cookbook 'graylog', git: 'git@github.com:chr4-cookbooks/graylog.git'
cookbook 'htpasswd', git: 'git@github.com:Youscribe/htpasswd-cookbook.git'
cookbook 'backup', git: 'git@github.com:Sheile/backup-cookbook.git' #fork from https://github.com/gofullstack/backup-cookbook
cookbook 'rackspacecloud', git: 'git@github.com:rackops/rackspacecloud.git'
cookbook 'simple_iptables', git: 'git@github.com:rtkwlf/cookbook-simple-iptables.git'
cookbook 'tomcat'
cookbook 'runit', git: 'git@github.com:hw-cookbooks/runit.git'
cookbook 'kibana_lwrp', git: 'git@github.com:lusis/chef-kibana.git', tag: 'v2.0.4'
cookbook 'beaver', git: 'git@github.com:alappe/cookbook-beaver.git'
cookbook 'libarchive', git: 'git@github.com:reset/libarchive-cookbook.git'
cookbook 'poise', git: 'git@github.com:poise/poise.git', tag: 'v1.0.12'
cookbook 'elkstack', git: 'git@github.com:rackspace-cookbooks/elkstack.git', tag: 'v6.0.2'
cookbook 'rackspace_monitoring', git: 'git@github.com:rackspace-cookbooks/rackspace_monitoring.git', tag: 'v1.1.1'
cookbook 'rsyslog', git: 'git@github.com:chef-cookbooks/rsyslog.git', tag: 'v2.2.0'
cookbook 'firewall', git: 'git@github.com:chef-cookbooks/firewall.git', tag: 'v1.6.2'
cookbook 'line', git: 'git@github.com:someara/line-cookbook.git', tag: 'v0.6.3'
cookbook 'cron', git: 'git@github.com:chef-cookbooks/cron.git', tag: 'v1.4.3'
cookbook 'newrelic_meetme_plugin', git: 'git@github.com:escapestudios-cookbooks/newrelic_meetme_plugin.git', tag: 'v0.3.0'
