name             'MrAwesomeDevOpsGuy'
maintainer       'MyBusiness'
maintainer_email 'dev@mybusiness.com'
license          'All Rights Reserved'
description      'Configures business specific roles'
version          '0.0.1'

supports 'amazon'
supports 'debian'
supports 'ubuntu'
